run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional useful linters
    - gofmt
    - goimports
    - goconst
    - gocyclo
    - misspell
    - unparam
    - unconvert
    - gocritic
    - revive
    - gosec
    - copyloopvar
    - whitespace
    - gofumpt

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/bit-chisel/docker-psa
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 25  # More lenient for this project
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "disableStutteringCheck"]
  gosec:
    excludes:
      - G204  # Allow subprocess with variable
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - ifElseChain  # Allow if-else chains
      - dupBranchBody  # Allow duplicate branch bodies for clarity
      - rangeValCopy  # Allow range value copies for readability
      - exitAfterDefer  # Allow exit after defer in debug code
      - emptyStringTest  # Allow len() > 0 style
      - octalLiteral  # Allow old octal style
      - elseif  # Allow else { if } style

issues:
  exclude-dirs:
    - tools
  exclude-rules:
    # Exclude debug code
    - path: main.go
      text: "debugFile.*unused"
      linters:
        - ineffassign
        - staticcheck
  max-same-issues: 0
  max-issues-per-linter: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
